name: demo workflow
on :
    push:
        branches:
        - main
jobs:
    demo_workflow:
        runs-on : ubuntu-latest
        steps:
        - name : checkout code
          uses: actions/checkout@v2
        - name: execute demo.py
          run: python demo.py
    
