name: security_secrets
on :
  push:
    branches:
    - main
jobs:
  secrets:
    runs-on : ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: get secret value
        env:
          username: ${{secrets.DB_USERNAME}}
          password: ${{secrets.DB_PASSWORD}}
        run: python secure.py




          
    
