name: External-dependencies
on :
  push:
    branches:
    - main
jobs:
  external_workflow:
    runs-on : ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install python required library
        run: pip install -r requirements.txt

      - name: execute test.py
        run: python test.py



          
    
